# Generated by Django 4.2.1 on 2023-06-24 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages_set",
                to="users.profile",
            ),
        ),
    ]
